[package]
name = "gif_transparency"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
anyhow = "1.0.75"
walkdir = "2.3.3"    # For traversing directories recursively
rayon = "1.7.0"      # For parallel processing
indicatif = "0.17.5" # For progress bars